intaro_api:
    resource: "@IntaroApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

intaro_book:
    resource: "@IntaroBookBundle/Resources/config/routing.yml"
    prefix:   /book
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
