intaro_api:
    resource: "@IntaroApiBundle/Resources/config/routing.yml"
    prefix:   /

intaro_book:
    resource: "@IntaroBookBundle/Resources/config/routing.yml"
    prefix:   /book
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

